# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

info:
    app:
        description: ${project.description}
        name: ${project.artifactId}
        version: ${project.version}
    
management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: ALWAYS         
    
server:
    port: 8003
    servlet:
        context-path: /jsync
    tomcat:
        threads:
            min-spare: 2
            max: 4
        
spring:
    jackson:
        date-format: “yyyy-MM-dd HH:mm:ss”
        deserialization:
            ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT: false
            ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: false
            FAIL_ON_UNKNOWN_PROPERTIES: false
            FAIL_ON_NULL_FOR_PRIMITIVES: true
            UNWRAP_ROOT_VALUE: false
        locale: de_DE
        property-naming-strategy: SNAKE_CASE
        serialization:
            INDENT_OUTPUT: true
            WRAP_ROOT_VALUE: false
            WRITE_DATES_AS_TIMESTAMPS: false
            WRITE_DATES_WITH_ZONE_ID: false
        time-zone: Europe/Berlin   
    mvc:
        locale: de_DE
        throw-exception-if-no-handler-found: true
    output:
        ansi:
            enabled: DETECT   
